using Microsoft.EntityFrameworkCore;

namespace Netstr.Extensions
{
    public static class DbExtensions
    {
        /// <summary>
        /// Ensures migrations are run for given <see cref="DbContext"/> during startup.
        /// </summary>
        public static IApplicationBuilder EnsureDbContextMigrations<T>(this IApplicationBuilder app) where T : DbContext
        {
            using var scope = app.ApplicationServices.CreateScope();
            using var context = scope.ServiceProvider.GetRequiredService<T>();

            if (context.Database.ProviderName?.Contains("Npgsql") == true)
            {
                // Ensure postgres is running if docker is used, and wait for connection
                for (int attempt = 1; attempt <= 10; attempt++)
                {
                    try
                    {
                        if (context.Database.CanConnect())
                        {
                            break;
                        }
                    }
                    catch
                    {
                        // Ignore connection failure during startup retry
                    }

                    if (attempt == 1)
                    {
                        try
                        {
                            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                            {
                                FileName = "docker",
                                Arguments = "start netstr-postgres",
                                UseShellExecute = false,
                                CreateNoWindow = true
                            })?.WaitForExit(2000);
                        }
                        catch
                        {
                            // Docker might not be installed or permissions not available
                        }
                    }

                    Thread.Sleep(1000);
                }

                try
                {
                    context.Database.Migrate();
                }
                catch
                {
                    // If migration history has a discrepancy, continue to EnsureTablesExist
                }

                EnsureTablesExist(context);
            }
            else
            {
                context.Database.EnsureCreated();
            }

            return app;
        }

        private static void EnsureTablesExist(DbContext context)
        {
            const string sql = @"
CREATE TABLE IF NOT EXISTS ""AdminUsers"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Username"" text NOT NULL,
    ""PasswordHash"" text NOT NULL,
    ""Salt"" text NOT NULL,
    ""NostrPublicKey"" text,
    ""Role"" text NOT NULL,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""LastLoginAt"" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AdminUsers_Username"" ON ""AdminUsers"" (""Username"");

CREATE TABLE IF NOT EXISTS ""PubkeyRules"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""PublicKey"" text NOT NULL,
    ""Status"" integer NOT NULL,
    ""CustomStorageQuotaBytes"" bigint,
    ""BlossomUploadBanned"" boolean NOT NULL DEFAULT FALSE,
    ""BanReason"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""ExpiresAt"" timestamp with time zone
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_PubkeyRules_PublicKey"" ON ""PubkeyRules"" (""PublicKey"");
ALTER TABLE ""PubkeyRules"" ADD COLUMN IF NOT EXISTS ""BlossomUploadBanned"" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS ""BannedEvents"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""EventId"" text NOT NULL,
    ""Reason"" text,
    ""BannedAt"" timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_BannedEvents_EventId"" ON ""BannedEvents"" (""EventId"");

CREATE TABLE IF NOT EXISTS ""ModerationReports"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""ReportEventId"" text,
    ""ReporterPubkey"" text NOT NULL,
    ""TargetPubkey"" text NOT NULL,
    ""TargetEventId"" text,
    ""Category"" text NOT NULL,
    ""Content"" text,
    ""Status"" integer NOT NULL,
    ""ResolutionNotes"" text,
    ""ResolvedByAdmin"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL,
    ""ResolvedAt"" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS ""ModerationAppeals"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""AppellantPubkey"" text NOT NULL,
    ""TargetEventId"" text,
    ""AppealMessage"" text NOT NULL,
    ""Status"" integer NOT NULL,
    ""ModeratorComment"" text,
    ""SubmittedAt"" timestamp with time zone NOT NULL,
    ""ReviewedAt"" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS ""ModerationAuditLogs"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""AdminIdentifier"" text NOT NULL,
    ""ActionType"" text NOT NULL,
    ""TargetIdentifier"" text NOT NULL,
    ""DetailsJson"" text,
    ""Timestamp"" timestamp with time zone NOT NULL
);
";
            try
            {
                context.Database.ExecuteSqlRaw(sql);
            }
            catch
            {
                // Non-critical fallback
            }
        }
    }
}
