// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_62Two_StageVanishFeature : object, Xunit.IClassFixture<NIP_62Two_StageVanishFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "62.feature"
#line hidden
        
        public NIP_62Two_StageVanishFeature(NIP_62Two_StageVanishFeature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-62 (Two-Stage Vanish)", "\tNostr-native way to request a complete reset of a key\'s fingerprint on the web.\n" +
                    "\tLibregram extends NIP-62 with a two-stage process: cancellable \"will to vanish\"" +
                    " \n\tfollowed by irreversible execution at ban_at.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table127 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table127.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 8
 testRunner.And("Alice is connected to relay", ((string)(null)), table127, "And ");
#line hidden
            TechTalk.SpecFlow.Table table128 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table128.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 11
 testRunner.And("Bob is connected to relay", ((string)(null)), table128, "And ");
#line hidden
            TechTalk.SpecFlow.Table table129 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table129.AddRow(new string[] {
                        "fe8d7a5726ea97ce6140f9fb06b1fe7d3259bcbf8de42c2a5d2ec9f8f0e2f614",
                        "f77f81a6a223eb15f81fee569161a4f729401a9cbc31bb69fef6a949b9d3c23a"});
#line 14
 testRunner.And("Charlie is connected to relay", ((string)(null)), table129, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Request to Vanish requires ban_at tag")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Request to Vanish requires ban_at tag")]
        public void RequestToVanishRequiresBan_AtTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Request to Vanish requires ban_at tag", "\tKind-62 without ban_at is rejected.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table130 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table130.AddRow(new string[] {
                            "ff1092c354d94060a185f8b5e4349499079872babe27b882fd4632efcdd001c2",
                            "Hello",
                            "1",
                            "",
                            "1728905459"});
                table130.AddRow(new string[] {
                            "9766e0efe45ecd90c508e66a8dd3eee3a7f16be33af87aded9fc779f40237d0e",
                            "I\'m outta here",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"]]",
                            "1728905470"});
#line 20
 testRunner.When("Alice publishes events", ((string)(null)), table130, "When ");
#line hidden
                TechTalk.SpecFlow.Table table131 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table131.AddRow(new string[] {
                            "OK",
                            "ff1092c354d94060a185f8b5e4349499079872babe27b882fd4632efcdd001c2",
                            "true"});
                table131.AddRow(new string[] {
                            "OK",
                            "9766e0efe45ecd90c508e66a8dd3eee3a7f16be33af87aded9fc779f40237d0e",
                            "false"});
#line 24
 testRunner.Then("Alice receives messages", ((string)(null)), table131, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Request to Vanish with ban_at creates pending")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Request to Vanish with ban_at creates pending")]
        public void RequestToVanishWithBan_AtCreatesPending()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Request to Vanish with ban_at creates pending", "\tKind-62 with valid future ban_at is accepted. Events NOT deleted.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table132 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table132.AddRow(new string[] {
                            "ff1092c354d94060a185f8b5e4349499079872babe27b882fd4632efcdd001c2",
                            "Hello",
                            "1",
                            "",
                            "1728905459"});
                table132.AddRow(new string[] {
                            "f45c291b8c4e3a164e68932f251e50b4182f4dfe2eca76081a7ca2d759568dfd",
                            "Hello Later",
                            "1",
                            "",
                            "1728905480"});
                table132.AddRow(new string[] {
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5",
                            "vanish will",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"ban_at\",\"2528905470\"]]",
                            "1728905470"});
#line 31
 testRunner.When("Alice publishes events", ((string)(null)), table132, "When ");
#line hidden
                TechTalk.SpecFlow.Table table133 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors"});
                table133.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75,5bc683a5d12133a9" +
                                "6ac5502c15fe1c2287986cff7baf6283600360e6bb01f627"});
#line 36
 testRunner.And("Charlie sends a subscription request abcd", ((string)(null)), table133, "And ");
#line hidden
                TechTalk.SpecFlow.Table table134 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table134.AddRow(new string[] {
                            "EVENT",
                            "abcd",
                            "f45c291b8c4e3a164e68932f251e50b4182f4dfe2eca76081a7ca2d759568dfd"});
                table134.AddRow(new string[] {
                            "EVENT",
                            "abcd",
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5"});
                table134.AddRow(new string[] {
                            "EVENT",
                            "abcd",
                            "ff1092c354d94060a185f8b5e4349499079872babe27b882fd4632efcdd001c2"});
                table134.AddRow(new string[] {
                            "EOSE",
                            "abcd",
                            ""});
#line 39
 testRunner.Then("Charlie receives messages", ((string)(null)), table134, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate pending vanish rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Duplicate pending vanish rejected")]
        public void DuplicatePendingVanishRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate pending vanish rejected", "\tSecond kind-62 while one pending is rejected.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table135 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table135.AddRow(new string[] {
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5",
                            "vanish will",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"ban_at\",\"2528905470\"]]",
                            "1728905470"});
                table135.AddRow(new string[] {
                            "dbb351bfcb8abac6e077cadf220a2dfece76376d4e2eff19c31860a633779021",
                            "vanish later",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"ban_at\",\"2628905490\"]]",
                            "1728905490"});
#line 48
 testRunner.When("Alice publishes events", ((string)(null)), table135, "When ");
#line hidden
                TechTalk.SpecFlow.Table table136 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table136.AddRow(new string[] {
                            "OK",
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5",
                            "true"});
                table136.AddRow(new string[] {
                            "OK",
                            "dbb351bfcb8abac6e077cadf220a2dfece76376d4e2eff19c31860a633779021",
                            "false"});
#line 52
 testRunner.Then("Alice receives messages", ((string)(null)), table136, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancel pending vanish within window")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Cancel pending vanish within window")]
        public void CancelPendingVanishWithinWindow()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancel pending vanish within window", "\tAction=cancel with reference to original event cancels pending vanish.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table137 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table137.AddRow(new string[] {
                            "5b1d0f938a672ae13a70860e43baa53ca78ef1ce227546486d753f14e2404170",
                            "vanish will",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"ban_at\",\"2528905470\"],[\"cancel_before\",\"1928905470\"]]",
                            "1728905470"});
                table137.AddRow(new string[] {
                            "d9149958a88c2fa31811ab265fd4308b06f9f4cf2e3d7225fdc130e37c5dcef0",
                            "cancel vanish",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"action\",\"cancel\"],[\"e\",\"5b1d0f938a672ae13a70860e43baa53" +
                                "ca78ef1ce227546486d753f14e2404170\"]]",
                            "1728905480"});
#line 59
 testRunner.When("Alice publishes events", ((string)(null)), table137, "When ");
#line hidden
                TechTalk.SpecFlow.Table table138 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table138.AddRow(new string[] {
                            "OK",
                            "5b1d0f938a672ae13a70860e43baa53ca78ef1ce227546486d753f14e2404170",
                            "true"});
                table138.AddRow(new string[] {
                            "OK",
                            "d9149958a88c2fa31811ab265fd4308b06f9f4cf2e3d7225fdc130e37c5dcef0",
                            "true"});
#line 63
 testRunner.Then("Alice receives messages", ((string)(null)), table138, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancel non-existent vanish rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Cancel non-existent vanish rejected")]
        public void CancelNon_ExistentVanishRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancel non-existent vanish rejected", "\tCancel without matching pending vanish is rejected.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table139 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table139.AddRow(new string[] {
                            "d690fb40e920e2933dd727c62bbbc137f15a84044eecfca3d96fe3cf2c78ca53",
                            "cancel phantom",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"action\",\"cancel\"],[\"e\",\"NONEXISTENT\"]]",
                            "1728905480"});
#line 70
 testRunner.When("Alice publishes events", ((string)(null)), table139, "When ");
#line hidden
                TechTalk.SpecFlow.Table table140 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table140.AddRow(new string[] {
                            "OK",
                            "d690fb40e920e2933dd727c62bbbc137f15a84044eecfca3d96fe3cf2c78ca53",
                            "false"});
#line 73
 testRunner.Then("Alice receives messages", ((string)(null)), table140, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Kind-5 deletion of kind-62 rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Kind-5 deletion of kind-62 rejected")]
        public void Kind_5DeletionOfKind_62Rejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kind-5 deletion of kind-62 rejected", "\tDelete request against a request to vanish has no effect.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table141 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table141.AddRow(new string[] {
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5",
                            "vanish will",
                            "62",
                            "[[\"relay\",\"ALL_RELAYS\"],[\"ban_at\",\"2528905470\"]]",
                            "1728905470"});
                table141.AddRow(new string[] {
                            "d0918ee16d6e7faf79bfbaec42cb6771a9c21fac630d41492745d8072a9b05e7",
                            "",
                            "5",
                            "[[\"e\", \"272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5\"]]",
                            "1728905471"});
#line 79
 testRunner.When("Alice publishes events", ((string)(null)), table141, "When ");
#line hidden
                TechTalk.SpecFlow.Table table142 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table142.AddRow(new string[] {
                            "OK",
                            "272256aaa438e89222e5cc58bda673dba4597ac40eea2e01dee7b6efd753cde5",
                            "true"});
                table142.AddRow(new string[] {
                            "OK",
                            "d0918ee16d6e7faf79bfbaec42cb6771a9c21fac630d41492745d8072a9b05e7",
                            "false"});
#line 83
 testRunner.Then("Alice receives messages", ((string)(null)), table142, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Relay tag must match")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-62 (Two-Stage Vanish)")]
        [Xunit.TraitAttribute("Description", "Relay tag must match")]
        public void RelayTagMustMatch()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Relay tag must match", "\tMissing/incorrect relay tag rejected. Correct one accepted.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table143 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "Tags",
                            "CreatedAt"});
                table143.AddRow(new string[] {
                            "760dd93c57151698628a28866366971d02e6a075c54bae7e84fd7740a90c0a2c",
                            "vanish no tag",
                            "62",
                            "",
                            "1728905470"});
                table143.AddRow(new string[] {
                            "4d7435a84d44fea8c41fa8ccd122502a44c2ac54c5d3bfeb512676697eca6168",
                            "vanish bad tag",
                            "62",
                            "[[\"relay\",\"blabla\"],[\"ban_at\",\"2528905470\"]]",
                            "1728905470"});
                table143.AddRow(new string[] {
                            "de57395f11aa96d286dd679c140fb04a21a0ad4eaae1465936c51c7be00fe1d9",
                            "vanish correct",
                            "62",
                            "[[\"relay\",\"ws://localhost/\"],[\"ban_at\",\"2528905470\"]]",
                            "1728905470"});
#line 90
 testRunner.When("Alice publishes events", ((string)(null)), table143, "When ");
#line hidden
                TechTalk.SpecFlow.Table table144 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "EventId",
                            "Success"});
                table144.AddRow(new string[] {
                            "OK",
                            "760dd93c57151698628a28866366971d02e6a075c54bae7e84fd7740a90c0a2c",
                            "false"});
                table144.AddRow(new string[] {
                            "OK",
                            "4d7435a84d44fea8c41fa8ccd122502a44c2ac54c5d3bfeb512676697eca6168",
                            "false"});
                table144.AddRow(new string[] {
                            "OK",
                            "de57395f11aa96d286dd679c140fb04a21a0ad4eaae1465936c51c7be00fe1d9",
                            "true"});
#line 95
 testRunner.Then("Alice receives messages", ((string)(null)), table144, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_62Two_StageVanishFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_62Two_StageVanishFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
