// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Netstr.Tests.NIPs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NIP_B7Feature : object, Xunit.IClassFixture<NIP_B7Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "B7.feature"
#line hidden
        
        public NIP_B7Feature(NIP_B7Feature.FixtureData fixtureData, Netstr_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NIPs", "NIP-B7", "\tBlossom media support.\n\tThe relay stores kind:10063 (User Server List) replaceab" +
                    "le events\n\tand provides HTTP endpoints for blob storage (BUD-01, BUD-02, BUD-11," +
                    " BUD-12).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
 testRunner.Given("a relay is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table149 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table149.AddRow(new string[] {
                        "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75",
                        "512a14752ed58380496920da432f1c0cdad952cd4afda3d9bfa51c2051f91b02"});
#line 8
 testRunner.And("Alice is connected to relay", ((string)(null)), table149, "And ");
#line hidden
            TechTalk.SpecFlow.Table table150 = new TechTalk.SpecFlow.Table(new string[] {
                        "PublicKey",
                        "PrivateKey"});
            table150.AddRow(new string[] {
                        "5bc683a5d12133a96ac5502c15fe1c2287986cff7baf6283600360e6bb01f627",
                        "3551fc7617f76632e4542992c0bc01fecb224de639c4b6a1e0956946e8bb8a29"});
#line 11
 testRunner.And("Bob is connected to relay", ((string)(null)), table150, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User publishes a kind:10063 server list event")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-B7")]
        [Xunit.TraitAttribute("Description", "User publishes a kind:10063 server list event")]
        public void UserPublishesAKind10063ServerListEvent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User publishes a kind:10063 server list event", "\tAlice publishes a kind:10063 event with server tags.\n\tThe relay should store it " +
                    "as a replaceable event and return it on subscription.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table151 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "CreatedAt",
                            "Signature",
                            "Tags"});
                table151.AddRow(new string[] {
                            "5d4d1109236e402555436c91019b599da5841542d3f430ed2b8b06f64c46130f",
                            "",
                            "10063",
                            "1780615585",
                            "",
                            "[[\"server\",\"https://cdn.example.com\"],[\"server\",\"https://blossom.self.hosted\"]]"});
#line 18
 testRunner.When("Alice publishes an event", ((string)(null)), table151, "When ");
#line hidden
                TechTalk.SpecFlow.Table table152 = new TechTalk.SpecFlow.Table(new string[] {
                            "Kinds"});
                table152.AddRow(new string[] {
                            "10063"});
#line 21
 testRunner.And("Bob sends a subscription request sub1", ((string)(null)), table152, "And ");
#line hidden
                TechTalk.SpecFlow.Table table153 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table153.AddRow(new string[] {
                            "EVENT",
                            "sub1",
                            "5d4d1109236e402555436c91019b599da5841542d3f430ed2b8b06f64c46130f"});
                table153.AddRow(new string[] {
                            "EOSE",
                            "sub1",
                            ""});
#line 24
 testRunner.Then("Bob receives messages", ((string)(null)), table153, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Kind:10063 is replaceable - newer event replaces older one")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-B7")]
        [Xunit.TraitAttribute("Description", "Kind:10063 is replaceable - newer event replaces older one")]
        public void Kind10063IsReplaceable_NewerEventReplacesOlderOne()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Kind:10063 is replaceable - newer event replaces older one", "\tAlice publishes a kind:10063 event, then publishes a newer one.\n\tOnly the newer " +
                    "event should be returned on subscription.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table154 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "CreatedAt",
                            "Signature",
                            "Tags"});
                table154.AddRow(new string[] {
                            "6a7cedcd64a2ec1761c1ddfec3bd5fffd77acaf730db805ffaa88515367cbe6e",
                            "",
                            "10063",
                            "1780615585",
                            "",
                            "[[\"server\",\"https://old.example.com\"]]"});
#line 32
 testRunner.When("Alice publishes an event", ((string)(null)), table154, "When ");
#line hidden
                TechTalk.SpecFlow.Table table155 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "CreatedAt",
                            "Signature",
                            "Tags"});
                table155.AddRow(new string[] {
                            "2a48099ff0c16e9a9c2d40ee039611e9a38e23f5c7fe9f4dd0b6e9182423a2ef",
                            "",
                            "10063",
                            "1780615586",
                            "",
                            "[[\"server\",\"https://new.example.com\"],[\"server\",\"https://cdn.blossom.cloud\"]]"});
#line 35
 testRunner.And("Alice publishes an event", ((string)(null)), table155, "And ");
#line hidden
                TechTalk.SpecFlow.Table table156 = new TechTalk.SpecFlow.Table(new string[] {
                            "Kinds"});
                table156.AddRow(new string[] {
                            "10063"});
#line 38
 testRunner.And("Bob sends a subscription request sub1", ((string)(null)), table156, "And ");
#line hidden
                TechTalk.SpecFlow.Table table157 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table157.AddRow(new string[] {
                            "EVENT",
                            "sub1",
                            "2a48099ff0c16e9a9c2d40ee039611e9a38e23f5c7fe9f4dd0b6e9182423a2ef"});
                table157.AddRow(new string[] {
                            "EOSE",
                            "sub1",
                            ""});
#line 41
 testRunner.Then("Bob receives messages", ((string)(null)), table157, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Different users can have different server lists")]
        [Xunit.TraitAttribute("FeatureTitle", "NIP-B7")]
        [Xunit.TraitAttribute("Description", "Different users can have different server lists")]
        public void DifferentUsersCanHaveDifferentServerLists()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Different users can have different server lists", "\tAlice and Bob each publish their own kind:10063 events.\n\tFiltering by author sho" +
                    "uld return only that user\'s server list.", tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table158 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Content",
                            "Kind",
                            "CreatedAt",
                            "Signature",
                            "Tags"});
                table158.AddRow(new string[] {
                            "310e9b4611b2b3e90d120775282f1cc3e29bf5205469744079138db7f388f9f0",
                            "",
                            "10063",
                            "1780615585",
                            "",
                            "[[\"server\",\"https://alice.blossom.com\"]]"});
#line 49
 testRunner.When("Alice publishes an event", ((string)(null)), table158, "When ");
#line hidden
                TechTalk.SpecFlow.Table table159 = new TechTalk.SpecFlow.Table(new string[] {
                            "Authors"});
                table159.AddRow(new string[] {
                            "5758137ec7f38f3d6c3ef103e28cd9312652285dab3497fe5e5f6c5c0ef45e75"});
#line 52
 testRunner.And("Bob sends a subscription request sub1", ((string)(null)), table159, "And ");
#line hidden
                TechTalk.SpecFlow.Table table160 = new TechTalk.SpecFlow.Table(new string[] {
                            "Type",
                            "Id",
                            "EventId"});
                table160.AddRow(new string[] {
                            "EVENT",
                            "sub1",
                            "310e9b4611b2b3e90d120775282f1cc3e29bf5205469744079138db7f388f9f0"});
                table160.AddRow(new string[] {
                            "EOSE",
                            "sub1",
                            ""});
#line 55
 testRunner.Then("Bob receives messages", ((string)(null)), table160, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NIP_B7Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NIP_B7Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
