// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netstr.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Netstr.Data.Migrations
{
    [DbContext(typeof(NetstrDbContext))]
    partial class NetstrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Netstr.Data.BlobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerPubkey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("OwnerPubkey", "UploadedAt");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("Netstr.Data.EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EventCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventDeduplication")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EventExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EventKind")
                        .HasColumnType("bigint");

                    b.Property<string>("EventPublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "EventIdIdx")
                        .IsUnique();

                    b.HasIndex(new[] { "EventKind", "EventPublicKey", "EventCreatedAt" }, "EventLookupIdx");

                    b.HasIndex(new[] { "EventPublicKey", "EventKind", "EventDeduplication" }, "ReplaceableEventsIdx")
                        .IsUnique()
                        .HasFilter("\n                    (\"EventKind\" = 0) OR \n                    (\"EventKind\" = 3) OR \n                    (\"EventKind\" >= 10000 AND \"EventKind\" < 20000) OR \n                    (\"EventKind\" >= 30000 AND \"EventKind\" < 40000)");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Netstr.Data.NotificationTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastAuthAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pubkey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Pubkey");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("NotificationTokens");
                });

            modelBuilder.Entity("Netstr.Data.PendingVanishEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CancelBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Executed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Irreversible")
                        .HasColumnType("boolean");

                    b.Property<string>("Pubkey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WillCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WillEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Pubkey");

                    b.HasIndex("Pubkey", "WillEventId")
                        .IsUnique();

                    b.ToTable("PendingVanishes");
                });

            modelBuilder.Entity("Netstr.Data.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("OtherValues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex(new[] { "Name", "Value", "EventId" }, "TagNameValueIdx")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Netstr.Data.TagEntity", b =>
                {
                    b.HasOne("Netstr.Data.EventEntity", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Netstr.Data.EventEntity", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
